export const books_data = [
  {
    author: "Hans Christian Andersen",
    country: "Denmark",
    imageLink: "images/fairy-tales.jpg",
    language: "Danish",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    pages: 784,
    title: "Fairy tales",
    year: 1836,
    id: 2,
    isPopular: false,
    category: "Fairy Tales",
  },
  {
    author: "Dante Alighieri",
    country: "Italy",
    imageLink: "images/the-divine-comedy.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    pages: 928,
    title: "The Divine Comedy",
    year: 1315,
    id: 3,
    isPopular: false,
    category: "Epic Poetry",
  },
  {
    author: "Bratt Wiliams",
    country: "Sumer and Akkadian Empire",
    imageLink: "images/the-epic-of-gilgamesh.jpg",
    language: "Akkadian",
    link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    pages: 160,
    title: "The Epic Of Gilgamesh",
    year: -1700,
    id: 4,
    isPopular: false,
    category: "Epic Poetry",
  },
  {
    author: "Andrew Austin",
    country: "Achaemenid Empire",
    imageLink: "images/the-book-of-job.jpg",
    language: "Hebrew",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 176,
    title: "The Book Of Job",
    year: -600,
    id: 5,
    isPopular: false,
    category: "Religious Text",
  },
  {
    author: "Lucas Miller",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    imageLink: "images/one-thousand-and-one-nights.jpg",
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 288,
    title: "One Thousand and One Nights",
    year: 1200,
    id: 6,
    isPopular: false,
    category: "Folk Tales",
  },
  {
    author: "Jenny Jordan",
    country: "Iceland",
    imageLink: "images/njals-saga.jpg",
    language: "Old Norse",
    link: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    pages: 384,
    title: "Njál's Saga",
    year: 1350,
    id: 7,
    isPopular: false,
    category: "Saga",
  },
  {
    author: "Jane Austen",
    country: "United Kingdom",
    imageLink: "images/pride-and-prejudice.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    pages: 226,
    title: "Pride and Prejudice",
    year: 1813,
    id: 8,
    isPopular: true,
    category: "Romance",
  },
  {
    author: "Honoré de Balzac",
    country: "France",
    imageLink: "images/le-pere-goriot.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    pages: 443,
    title: "Le Père Goriot",
    year: 1835,
    id: 9,
    isPopular: false,
    category: "Realism",
  },
  {
    author: "Samuel Beckett",
    country: "Republic of Ireland",
    imageLink: "images/molloy-malone-dies-the-unnamable.jpg",
    language: "French, English",
    link: "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    pages: 256,
    title: "Molloy, Malone Dies, The Unnamable, the trilogy",
    year: 1952,
    id: 10,
    isPopular: true,
    category: "Modernist",
  },
  {
    author: "Giovanni Boccaccio",
    country: "Italy",
    imageLink: "images/the-decameron.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/The_Decameron\n",
    pages: 1024,
    title: "The Decameron",
    year: 1351,
    id: 11,
    isPopular: false,
    category: "Collection of Stories",
  },
  {
    author: "Jorge Luis Borges",
    country: "Argentina",
    imageLink: "images/ficciones.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Ficciones\n",
    pages: 224,
    title: "Ficciones",
    year: 1965,
    id: 12,
    isPopular: true,
    category: "Fiction",
  },
  {
    author: "Emily Brontë",
    country: "United Kingdom",
    imageLink: "images/wuthering-heights.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    pages: 342,
    title: "Wuthering Heights",
    year: 1847,
    id: 13,
    isPopular: false,
    category: "Gothic Fiction",
  },
  {
    author: "Albert Camus",
    country: "Algeria, French Empire",
    imageLink: "images/l-etranger.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    pages: 185,
    title: "The Stranger",
    year: 1942,
    id: 14,
    isPopular: false,
    category: "Philosophical Fiction",
  },
  {
    author: "Paul Celan",
    country: "Romania, France",
    imageLink: "images/poems-paul-celan.jpg",
    language: "German",
    link: "\n",
    pages: 320,
    title: "Poems, Paul Celan",
    year: 1952,
    id: 15,
    isPopular: true,
    category: "Poetry",
  },
  {
    author: "Louis-Ferdinand Céline",
    country: "France",
    imageLink: "images/voyage-au-bout-de-la-nuit.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    pages: 505,
    title: "Journey to the End of the Night",
    year: 1932,
    id: 16,
    isPopular: false,
    category: "Modernist",
  },
  {
    author: "Miguel de Cervantes",
    country: "Spain",
    imageLink: "images/don-quijote-de-la-mancha.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Don_Quixote\n",
    pages: 1056,
    title: "Don Quijote De La Mancha",
    year: 1610,
    id: 17,
    isPopular: false,
    category: "Novel",
  },
  {
    author: "Geoffrey Chaucer",
    country: "England",
    imageLink: "images/the-canterbury-tales.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    pages: 544,
    title: "The Canterbury Tales",
    year: 1450,
    id: 18,
    isPopular: false,
    category: "Poetry",
  },
  {
    author: "Anton Chekhov",
    country: "Russia",
    imageLink: "images/stories-of-anton-chekhov.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
    pages: 194,
    title: "Stories, Anton Chekhov",
    year: 1886,
    id: 19,
    isPopular: true,
    category: "Short Stories",
  },
  {
    author: "Joseph Conrad",
    country: "Poland",
    imageLink: "images/heart-of-darkness.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Heart_of_Darkness",
    pages: 368,
    title: "Heart of Darkness",
    year: 1899,
    id: 20,
    isPopular: true,
    category: "Novella",
  },
  {
    author: "Daniel Defoe",
    country: "England",
    imageLink: "images/robinson-crusoe.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Robinson_Crusoe",
    pages: 320,
    title: "Robinson Crusoe",
    year: 1719,
    id: 21,
    isPopular: true,
    category: "Adventure",
  },
  {
    author: "Charles Dickens",
    country: "United Kingdom",
    imageLink: "images/a-tale-of-two-cities.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/A_Tale_of_Two_Cities",
    pages: 544,
    title: "A Tale of Two Cities",
    year: 1859,
    id: 22,
    isPopular: true,
    category: "Historical Fiction",
  },
  {
    author: "Thomas Hardy",
    country: "United Kingdom",
    imageLink: "images/tess-of-the-d-urbervilles.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Tess_of_the_d%27Urbervilles",
    pages: 410,
    title: "Tess of the d'Urbervilles",
    year: 1891,
    id: 23,
    isPopular: false,
    category: "Tragedy",
  },
  {
    author: "Ernest Hemingway",
    country: "United States",
    imageLink: "images/the-old-man-and-the-sea.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea",
    pages: 128,
    title: "The Old Man and the Sea",
    year: 1952,
    id: 24,
    isPopular: true,
    category: "Novella",
  },
  {
    author: "Herman Melville",
    country: "United States",
    imageLink: "images/moby-dick.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Moby-Dick",
    pages: 720,
    title: "Moby-Dick",
    year: 1851,
    id: 25,
    isPopular: false,
    category: "Adventure",
  },
  {
    author: "Harper Lee",
    country: "United States",
    imageLink: "images/to-kill-a-mockingbird.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/To_Kill_a_Mockingbird",
    pages: 281,
    title: "To Kill a Mockingbird",
    year: 1960,
    id: 26,
    isPopular: true,
    category: "Drama",
  },
  {
    author: "Mikhail Bulgakov",
    country: "Soviet Union",
    imageLink: "images/the-master-and-margarita.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/The_Master_and_Margarita",
    pages: 404,
    title: "The Master and Margarita",
    year: 1967,
    id: 27,
    isPopular: false,
    category: "Fantasy",
  },
  {
    author: "George Orwell",
    country: "United Kingdom",
    imageLink: "images/1984.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four",
    pages: 328,
    title: "1984",
    year: 1949,
    id: 28,
    isPopular: true,
    category: "Dystopian",
  },
  {
    author: "Vladimir Nabokov",
    country: "Russia, United States",
    imageLink: "images/lolita.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Lolita",
    pages: 336,
    title: "Lolita",
    year: 1955,
    id: 29,
    isPopular: true,
    category: "Literary Fiction",
  },
  {
    author: "F. Scott Fitzgerald",
    country: "United States",
    imageLink: "images/the-great-gatsby.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/The_Great_Gatsby",
    pages: 180,
    title: "The Great Gatsby",
    year: 1925,
    id: 30,
    isPopular: true,
    category: "Classic",
  },
  {
    author: "William Golding",
    country: "United Kingdom",
    imageLink: "images/lord-of-the-flies.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Lord_of_the_Flies",
    pages: 224,
    title: "Lord of the Flies",
    year: 1954,
    id: 31,
    isPopular: true,
    category: "Psychological Fiction",
  },
  {
    author: "John Steinbeck",
    country: "United States",
    imageLink: "images/of-mice-and-men.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Of_Mice_and_Men",
    pages: 112,
    title: "Of Mice and Men",
    year: 1937,
    id: 32,
    isPopular: true,
    category: "Drama",
  },
  {
    author: "Virginia Woolf",
    country: "United Kingdom",
    imageLink: "images/mrs-dalloway.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Mrs_Dalloway",
    pages: 216,
    title: "Mrs Dalloway",
    year: 1925,
    id: 33,
    isPopular: true,
    category: "Modernism",
  },
  {
    author: "E. M. Forster",
    country: "United Kingdom",
    imageLink: "images/a-passage-to-india.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/A_Passage_to_India",
    pages: 368,
    title: "A Passage to India",
    year: 1924,
    id: 34,
    isPopular: false,
    category: "Historical Fiction",
  },
  {
    author: "D. H. Lawrence",
    country: "United Kingdom",
    imageLink: "images/sons-and-lovers.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Sons_and_Lovers",
    pages: 480,
    title: "Sons and Lovers",
    year: 1913,
    id: 35,
    isPopular: false,
    category: "Romantic Fiction",
  },
  {
    author: "Leo Tolstoy",
    country: "Russia",
    imageLink: "images/war-and-peace.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/War_and_Peace",
    pages: 1225,
    title: "War and Peace",
    year: 1869,
    id: 36,
    isPopular: true,
    category: "Historical Fiction",
  },
];
export const category = [
  "Magical Realism",
  "Romance",
  "Tragedy/Philosophy",
  "Satire",
  "Historical Fiction",
  "Regional Fiction",
  "Psychological Fiction",
  "Adventure",
  "Epic Poetry",
  "Drama",
  "Modernist Literature",
  "Surrealism",
  "Existentialism",
  "Literary Fiction",
  "Poetry",
  "Fairy Tales",
  "Epic Poetry",
  "Religious Text",
  "Folk Tales",
  "Saga",
  "Romance",
  "Realism",
  "Modernist",
  "Collection of Stories",
  "Fiction",
  "Gothic Fiction",
  "Philosophical Fiction",
  "Poetry",
  "Modernist",
  "Novel",
  "Poetry",
  "Short Stories",
  "Novella",
  "Adventure",
  "Historical Fiction",
  "Tragedy",
  "Novella",
  "Adventure",
  "Drama",
  "Fantasy",
  "Dystopian",
  "Literary Fiction",
  "Classic",
  "Psychological Fiction",
  "Drama",
  "Modernism",
  "Historical Fiction",
  "Romantic Fiction",
  "Historical Fiction",
];
