export const baseUrl =
    "https://raw.githubusercontent.com/benoitvallon/100-best-books/master/static/";

const mock = [
   {
      "author": "Chinua Achebe",
      "country": "Nigeria",
      "imageLink": "images/things-fall-apart.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
      "pages": 209,
      "title": "Things Fall Apart",
      "year": 1958,
      "id": 1,
      "isPopular": false,
      
    },
    {
      "author": "Hans Christian Andersen",
      "country": "Denmark",
      "imageLink": "images/fairy-tales.jpg",
      "language": "Danish",
      "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
      "pages": 784,
      "title": "Fairy tales",
      "year": 1836,
      "id": 2,
      "isPopular": false,
    },
    {
      "author": "Dante Alighieri",
      "country": "Italy",
      "imageLink": "images/the-divine-comedy.jpg",
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
      "pages": 928,
      "title": "The Divine Comedy",
      "year": 1315,
      "id": 3,
      "isPopular": false,
    },
    {
      "author": "Bratt Wiliams",
      "country": "Sumer and Akkadian Empire",
      "imageLink": "images/the-epic-of-gilgamesh.jpg",
      "language": "Akkadian",
      "link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
      "pages": 160,
      "title": "The Epic Of Gilgamesh",
      "year": -1700,
      "id": 4,
      "isPopular": false,
    },
    {
      "author": "Andrew Austin",
      "country": "Achaemenid Empire",
      "imageLink": "images/the-book-of-job.jpg",
      "language": "Hebrew",
      "link": "https://en.wikipedia.org/wiki/Book_of_Job\n",
      "pages": 176,
      "title": "The Book Of Job",
      "year": -600,
      "id": 5,
      "isPopular": false,
    },
    {
      "author": "Lucas Miller",
      "country": "India/Iran/Iraq/Egypt/Tajikistan",
      "imageLink": "images/one-thousand-and-one-nights.jpg",
      "language": "Arabic",
      "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
      "pages": 288,
      "title": "One Thousand and One Nights",
      "year": 1200,
      "id": 6,
      "isPopular": false,
    },
    {
      "author": "Jenny Jordan",
      "country": "Iceland",
      "imageLink": "images/njals-saga.jpg",
      "language": "Old Norse",
      "link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
      "pages": 384,
      "title": "Nj\u00e1l's Saga",
      "year": 1350,
      "id": 7,
      "isPopular": false,
    },
    {
      "author": "Jane Austen",
      "country": "United Kingdom",
      "imageLink": "images/pride-and-prejudice.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
      "pages": 226,
      "title": "Pride and Prejudice",
      "year": 1813,
      "id": 8,
      "isPopular": true,
    },
    {
      "author": "Honor\u00e9 de Balzac",
      "country": "France",
      "imageLink": "images/le-pere-goriot.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
      "pages": 443,
      "title": "Le P\u00e8re Goriot",
      "year": 1835,
      "id": 9,
      "isPopular": false,
    },
    {
      "author": "Samuel Beckett",
      "country": "Republic of Ireland",
      "imageLink": "images/molloy-malone-dies-the-unnamable.jpg",
      "language": "French, English",
      "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
      "pages": 256,
      "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
      "year": 1952,
      "id": 10,
      "isPopular": true,
    },
    {
      "author": "Giovanni Boccaccio",
      "country": "Italy",
      "imageLink": "images/the-decameron.jpg",
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/The_Decameron\n",
      "pages": 1024,
      "title": "The Decameron",
      "year": 1351,
      "id": 11,
      "isPopular": false,
    },
    {
      "author": "Jorge Luis Borges",
      "country": "Argentina",
      "imageLink": "images/ficciones.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Ficciones\n",
      "pages": 224,
      "title": "Ficciones",
      "year": 1965,
      "id": 12,
      "isPopular": true,
    },
    {
      "author": "Emily Bront\u00eb",
      "country": "United Kingdom",
      "imageLink": "images/wuthering-heights.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
      "pages": 342,
      "title": "Wuthering Heights",
      "year": 1847,
      "id": 13,
      "isPopular": false,
    },
    {
      "author": "Albert Camus",
      "country": "Algeria, French Empire",
      "imageLink": "images/l-etranger.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
      "pages": 185,
      "title": "The Stranger",
      "year": 1942,
      "id": 14,
      "isPopular": false,
    },
    {
      "author": "Paul Celan",
      "country": "Romania, France",
      "imageLink": "images/poems-paul-celan.jpg",
      "language": "German",
      "link": "\n",
      "pages": 320,
      "title": "Poems, Paul Celan",
      "year": 1952,
      "id": 15,
      "isPopular": true,
    },
    {
      "author": "Louis-Ferdinand C\u00e9line",
      "country": "France",
      "imageLink": "images/voyage-au-bout-de-la-nuit.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
      "pages": 505,
      "title": "Journey to the End of the Night",
      "year": 1932,
      "id": 16,
      "isPopular": false,
    },
    {
      "author": "Miguel de Cervantes",
      "country": "Spain",
      "imageLink": "images/don-quijote-de-la-mancha.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
      "pages": 1056,
      "title": "Don Quijote De La Mancha",
      "year": 1610,
      "id": 17,
      "isPopular": false,
    },
    {
      "author": "Geoffrey Chaucer",
      "country": "England",
      "imageLink": "images/the-canterbury-tales.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
      "pages": 544,
      "title": "The Canterbury Tales",
      "year": 1450,
      "id": 18,
      "isPopular": false,
    },
    {
      "author": "Anton Chekhov",
      "country": "Russia",
      "imageLink": "images/stories-of-anton-chekhov.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
      "pages": 194,
      "title": "Stories, Anton Chekhov",
      "year": 1886,
      "id": 19,
      "isPopular": false,
    },
    {
      "author": "Joseph Conrad",
      "country": "United Kingdom",
      "imageLink": "images/nostromo.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Nostromo\n",
      "pages": 320,
      "title": "Nostromo",
      "year": 1904,
      "id": 20,
      "isPopular": false,
    },
    {
      "author": "Charles Dickens",
      "country": "United Kingdom",
      "imageLink": "images/great-expectations.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Great_Expectations\n",
      "pages": 194,
      "title": "Great Expectations",
      "year": 1861,
      "id": 21,
      "isPopular": false,
    },
    {
      "author": "Denis Diderot",
      "country": "France",
      "imageLink": "images/jacques-the-fatalist.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
      "pages": 596,
      "title": "Jacques the Fatalist",
      "year": 1796,
      "id": 22,
      "isPopular": false,
    },
    {
      "author": "Alfred D\u00f6blin",
      "country": "Germany",
      "imageLink": "images/berlin-alexanderplatz.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
      "pages": 600,
      "title": "Berlin Alexanderplatz",
      "year": 1929,
      "id": 23,
      "isPopular": false,
    },
    {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "imageLink": "images/crime-and-punishment.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
      "pages": 551,
      "title": "Crime and Punishment",
      "year": 1866,
      "id": 24,
      "isPopular": false,
    },
    {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "imageLink": "images/the-idiot.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/The_Idiot\n",
      "pages": 656,
      "title": "The Idiot",
      "year": 1869,
      "id": 25,
      "isPopular": false,
    },
    {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "imageLink": "images/the-possessed.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
      "pages": 768,
      "title": "The Possessed",
      "year": 1872,
      "id": 26,
      "isPopular": false,
    },
    {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "imageLink": "images/the-brothers-karamazov.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
      "pages": 824,
      "title": "The Brothers Karamazov",
      "year": 1880,
      "id": 27,
      "isPopular": false,
    },
    {
      "author": "George Eliot",
      "country": "United Kingdom",
      "imageLink": "images/middlemarch.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Middlemarch\n",
      "pages": 800,
      "title": "Middlemarch",
      "year": 1871,
      "id": 28,
      "isPopular": false,
    },
    {
      "author": "Ralph Ellison",
      "country": "United States",
      "imageLink": "images/invisible-man.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Invisible_Man\n",
      "pages": 581,
      "title": "Invisible Man",
      "year": 1952,
      "id": 29,
      "isPopular": false,
    },
    {
      "author": "Euripides",
      "country": "Greece",
      "imageLink": "images/medea.jpg",
      "language": "Greek",
      "link": "https://en.wikipedia.org/wiki/Medea_(play)\n",
      "pages": 104,
      "title": "Medea",
      "year": 1990,
      "id": 30,
      "isPopular": false,
    },
    {
      "author": "William Faulkner",
      "country": "United States",
      "imageLink": "images/absalom-absalom.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
      "pages": 313,
      "title": "Absalom, Absalom!",
      "year": 1936,
      "id": 31,
      "isPopular": false,
    },
    {
      "author": "William Faulkner",
      "country": "United States",
      "imageLink": "images/the-sound-and-the-fury.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
      "pages": 326,
      "title": "The Sound and the Fury",
      "year": 1929,
      "id": 32,
      "isPopular": false,
    },
    {
      "author": "Gustave Flaubert",
      "country": "France",
      "imageLink": "images/madame-bovary.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Madame_Bovary\n",
      "pages": 528,
      "title": "Madame Bovary",
      "year": 1857,
      "id": 33,
      "isPopular": false,
    },
    {
      "author": "Gustave Flaubert",
      "country": "France",
      "imageLink": "images/l-education-sentimentale.jpg",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Sentimental_Education\n",
      "pages": 606,
      "title": "Sentimental Education",
      "year": 1869,
      "id": 34,
      "isPopular": false,
    },
    {
      "author": "Federico Garc\u00eda Lorca",
      "country": "Spain",
      "imageLink": "images/gypsy-ballads.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Gypsy_Ballads\n",
      "pages": 218,
      "title": "Gypsy Ballads",
      "year": 1928,
      "id": 35,
      "isPopular": false,
    },
    {
      "author": "Gabriel Garc\u00eda M\u00e1rquez",
      "country": "Colombia",
      "imageLink": "images/one-hundred-years-of-solitude.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n",
      "pages": 417,
      "title": "One Hundred Years of Solitude",
      "year": 1967,
      "id": 36,
      "isPopular": false,
    },
    {
      "author": "Gabriel Garc\u00eda M\u00e1rquez",
      "country": "Colombia",
      "imageLink": "images/love-in-the-time-of-cholera.jpg",
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n",
      "pages": 368,
      "title": "Love in the Time of Cholera",
      "year": 1985,
      "id": 37,
      "isPopular": false,
    },
    {
      "author": "Johann Wolfgang von Goethe",
      "country": "Saxe-Weimar",
      "imageLink": "images/faust.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
      "pages": 158,
      "title": "faust",
      "year": 1832,
      "id": 38,
      "isPopular": false, 
    },
    {
      "author": "Nikolai Gogol",
      "country": "Russia",
      "imageLink": "images/dead-souls.jpg",
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/Dead_Souls\n",
      "pages": 432,
      "title": "Dead Souls",
      "year": 1842,
      "id": 39,
      "isPopular": false,
    },
    {
      "author": "G\u00fcnter Grass",
      "country": "Germany",
      "imageLink": "images/the-tin-drum.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/The_Tin_Drum\n",
      "pages": 600,
      "title": "The Tin Drum",
      "year": 1959,
      "id": 40,
      "isPopular": false,
    },
    {
      "author": "Jo\u00e3o Guimar\u00e3es Rosa",
      "country": "Brazil",
      "imageLink": "images/the-devil-to-pay-in-the-backlands.jpg",
      "language": "Portuguese",
      "link": "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n",
      "pages": 494,
      "title": "The Devil to Pay in the Backlands",
      "year": 1956,
      "id": 41,
      "isPopular": false,
    },
    {
      "author": "Knut Hamsun",
      "country": "Norway",
      "imageLink": "images/hunger.jpg",
      "language": "Norwegian",
      "link": "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n",
      "pages": 176,
      "title": "Hunger",
      "year": 1890,
      "id": 42,
      "isPopular": false,
    },
    {
      "author": "Ernest Hemingway",
      "country": "United States",
      "imageLink": "images/the-old-man-and-the-sea.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
      "pages": 128,
      "title": "The Old Man and the Sea",
      "year": 1952,
      "id": 43,
      "isPopular": false,
    },
    {
      "author": "Homer",
      "country": "Greece",
      "imageLink": "images/the-iliad-of-homer.jpg",
      "language": "Greek",
      "link": "https://en.wikipedia.org/wiki/Iliad\n",
      "pages": 608,
      "title": "Iliad",
      "year": -735,
      "id": 44,
      "isPopular": false,
    },
    {
      "author": "Homer",
      "country": "Greece",
      "imageLink": "images/the-odyssey-of-homer.jpg",
      "language": "Greek",
      "link": "https://en.wikipedia.org/wiki/Odyssey\n",
      "pages": 374,
      "title": "Odyssey",
      "year": -800,
      "id": 45,
      "isPopular": false,
    },
    {
      "author": "Henrik Ibsen",
      "country": "Norway",
      "imageLink": "images/a-Dolls-house.jpg",
      "language": "Norwegian",
      "link": "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
      "pages": 68,
      "title": "A Doll's House",
      "year": 1879,
      "id": 46,
      "isPopular": false,
    },
    {
      "author": "James Joyce",
      "country": "Irish Free State",
      "imageLink": "images/ulysses.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Ulysses_(novel)\n",
      "pages": 228,
      "title": "Ulysses",
      "year": 1922,
      "id": 47,
      "isPopular": false,
    },
    {
      "author": "Franz Kafka",
      "country": "Czechoslovakia",
      "imageLink": "images/stories-of-franz-kafka.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n",
      "pages": 488,
      "title": "Stories",
      "year": 1924,
      "id": 48,
      "isPopular": false,
    },
    {
      "author": "Franz Kafka",
      "country": "Czechoslovakia",
      "imageLink": "images/the-trial.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/The_Trial\n",
      "pages": 160,
      "title": "The Trial",
      "year": 1925,
      "id": 49,
      "isPopular": false,
    },
    {
      "author": "Franz Kafka",
      "country": "Czechoslovakia",
      "imageLink": "images/the-castle.jpg",
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
      "pages": 352,
      "title": "The Castle",
      "year": 1926,
      "id": 50,
      "isPopular": false,
    },
    {
      "author": "K\u0101lid\u0101sa",
      "country": "India",
      "imageLink": "images/the-recognition-of-shakuntala.jpg",
      "language": "Sanskrit",
      "link": "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n",
      "pages": 147,
      "title": "The recognition of Shakuntala",
      "year": 150,
      "id": 51,
      "isPopular": false,
    },
    {
      "author": "Yasunari Kawabata",
      "country": "Japan",
      "imageLink": "images/the-sound-of-the-mountain.jpg",
      "language": "Japanese",
      "link": "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n",
      "pages": 288,
      "title": "The Sound of the Mountain",
      "year": 1954,
      "id": 52,
      "isPopular": false,
    },
    {
      "author": "Nikos Kazantzakis",
      "country": "Greece",
      "imageLink": "images/zorba-the-greek.jpg",
      "language": "Greek",
      "link": "https://en.wikipedia.org/wiki/Zorba_the_Greek\n",
      "pages": 368,
      "title": "Zorba the Greek",
      "year": 1946,
      "id": 53,
      "isPopular": false,
    },
    {
      "author": "D. H. Lawrence",
      "country": "United Kingdom",
      "imageLink": "images/sons-and-lovers.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Sons_and_Lovers\n",
      "pages": 432,
      "title": "Sons and Lovers",
      "year": 1913,
      "id": 54,
      "isPopular": false,
    },
    {
      "author": "Halld\u00f3r Laxness",
      "country": "Iceland",
      "imageLink": "images/independent-people.jpg",
      "language": "Icelandic",
      "link": "https://en.wikipedia.org/wiki/Independent_People\n",
      "pages": 470,
      "title": "Independent People",
      "year": 1934,
      "id": 55,
      "isPopular": false,
    },
    {
      "author": "Giacomo Leopardi",
      "country": "Italy",
      "imageLink": "images/poems-giacomo-leopardi.jpg",
      "language": "Italian",
      "link": "\n",
      "pages": 184,
      "title": "Poems",
      "year": 1818,
      "id": 56,
      "isPopular": false,
    },
    {
      "author": "Doris Lessing",
      "country": "United Kingdom",
      "imageLink": "images/the-golden-notebook.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Golden_Notebook\n",
      "pages": 688,
      "title": "The Golden Notebook",
      "year": 1962,
      "id": 57,
      "isPopular": false,
    },
    {
      "author": "Astrid Lindgren",
      "country": "Sweden",
      "imageLink": "images/pippi-longstocking.jpg",
      "language": "Swedish",
      "link": "https://en.wikipedia.org/wiki/Pippi_Longstocking\n",
      "pages": 160,
      "title": "Pippi Longstocking",
      "year": 1945,
      "id": 58,
      "isPopular": false,
    },

  {
    "author": "Gabriel García Márquez",
    "country": "Colombia",
    "imageLink": "images/one-hundred-years-of-solitude.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n",
    "pages": 417,
    "title": "One Hundred Years of Solitude",
    "year": 1967,
    "id": 36,
    "isPopular": false,
    "category": "Magical Realism"
  },
  {
    "author": "Gabriel García Márquez",
    "country": "Colombia",
    "imageLink": "images/love-in-the-time-of-cholera.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n",
    "pages": 368,
    "title": "Love in the Time of Cholera",
    "year": 1985,
    "id": 37,
    "isPopular": false,
    "category": "Romance"
  },
  {
    "author": "Johann Wolfgang von Goethe",
    "country": "Saxe-Weimar",
    "imageLink": "images/faust.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
    "pages": 158,
    "title": "Faust",
    "year": 1832,
    "id": 38,
    "isPopular": false,
    "category": "Tragedy/Philosophy"
  },
  {
    "author": "Nikolai Gogol",
    "country": "Russia",
    "imageLink": "images/dead-souls.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Dead_Souls\n",
    "pages": 432,
    "title": "Dead Souls",
    "year": 1842,
    "id": 39,
    "isPopular": false,
    "category": "Satire"
  },
  {
    "author": "Günter Grass",
    "country": "Germany",
    "imageLink": "images/the-tin-drum.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Tin_Drum\n",
    "pages": 600,
    "title": "The Tin Drum",
    "year": 1959,
    "id": 40,
    "isPopular": false,
    "category": "Historical Fiction"
  },
  {
    "author": "João Guimarães Rosa",
    "country": "Brazil",
    "imageLink": "images/the-devil-to-pay-in-the-backlands.jpg",
    "language": "Portuguese",
    "link": "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n",
    "pages": 494,
    "title": "The Devil to Pay in the Backlands",
    "year": 1956,
    "id": 41,
    "isPopular": false,
    "category": "Regional Fiction"
  },
  {
    "author": "Knut Hamsun",
    "country": "Norway",
    "imageLink": "images/hunger.jpg",
    "language": "Norwegian",
    "link": "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n",
    "pages": 176,
    "title": "Hunger",
    "year": 1890,
    "id": 42,
    "isPopular": false,
    "category": "Psychological Fiction"
  },
  {
    "author": "Ernest Hemingway",
    "country": "United States",
    "imageLink": "images/the-old-man-and-the-sea.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
    "pages": 128,
    "title": "The Old Man and the Sea",
    "year": 1952,
    "id": 43,
    "isPopular": false,
    "category": "Adventure"
  },
  {
    "author": "Homer",
    "country": "Greece",
    "imageLink": "images/the-iliad-of-homer.jpg",
    "language": "Greek",
    "link": "https://en.wikipedia.org/wiki/Iliad\n",
    "pages": 608,
    "title": "Iliad",
    "year": -735,
    "id": 44,
    "isPopular": false,
    "category": "Epic Poetry"
  },
  {
    "author": "Homer",
    "country": "Greece",
    "imageLink": "images/the-odyssey-of-homer.jpg",
    "language": "Greek",
    "link": "https://en.wikipedia.org/wiki/Odyssey\n",
    "pages": 374,
    "title": "Odyssey",
    "year": -800,
    "id": 45,
    "isPopular": false,
    "category": "Epic Poetry"
  },
  {
    "author": "Henrik Ibsen",
    "country": "Norway",
    "imageLink": "images/a-Dolls-house.jpg",
    "language": "Norwegian",
    "link": "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
    "pages": 68,
    "title": "A Doll's House",
    "year": 1879,
    "id": 46,
    "isPopular": false,
    "category": "Drama"
  },
  {
    "author": "James Joyce",
    "country": "Irish Free State",
    "imageLink": "images/ulysses.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Ulysses_(novel)\n",
    "pages": 228,
    "title": "Ulysses",
    "year": 1922,
    "id": 47,
    "isPopular": false,
    "category": "Modernist Literature"
  },
  {
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "imageLink": "images/stories-of-franz-kafka.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n",
    "pages": 488,
    "title": "Stories",
    "year": 1924,
    "id": 48,
    "isPopular": false,
    "category": "Surrealism"
  },
  {
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "imageLink": "images/the-trial.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Trial\n",
    "pages": 160,
    "title": "The Trial",
    "year": 1925,
    "id": 49,
    "isPopular": false,
    "category": "Existentialism"
  },
  {
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "imageLink": "images/the-castle.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
    "pages": 352,
    "title": "The Castle",
    "year": 1926,
    "id": 50,
    "isPopular": false,
    "category": "Existentialism"
  },
  {
    "author": "Kālidāsa",
    "country": "India",
    "imageLink": "images/the-recognition-of-shakuntala.jpg",
    "language": "Sanskrit",
    "link": "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n",
    "pages": 147,
    "title": "The Recognition of Shakuntala",
    "year": 150,
    "id": 51,
    "isPopular": false,
    "category": "Epic Poetry"
  },
  {
    "author": "Yasunari Kawabata",
    "country": "Japan",
    "imageLink": "images/the-sound-of-the-mountain.jpg",
    "language": "Japanese",
    "link": "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n",
    "pages": 288,
    "title": "The Sound of the Mountain",
    "year": 1954,
    "id": 52,
    "isPopular": false,
    "category": "Literary Fiction"
  }
];

export default mock;